### PR TITLE
Automatic formatting of Python files

### PR DESCRIPTION
**Pull request by Y0sh1dk**
- Adds `black` as the default formatter for the vscode worksapce, python files will now be formatted on save.
 - Formats all files with `black`

### CODE REVIEW

**Comment by LachlanCourt** [comment]
I haven't looked at this too closely but have you/can you run this with the `ignore-rev` flag to not clutter the commit history? 🤔 It's changing like half the source 😂

**Comment by Y0sh1dk** [comment]
@LachlanCourt I've added a `.git-blame-ignore-revs` file which seems to do the trick in vscode with [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens). However, feel free to revert the formatting commit and push that yourself if you would like.

**Review by LachlanCourt — APPROVED** [review]
I'm gonna be a pretentious twat about this and do that hahahaha no kudos here just for formatting :p

**Comment by Y0sh1dk** [comment]
> I'm gonna be a pretentious twat about this and do that hahahaha no kudos here just for formatting :p

No worries at all :P

**Pull request merged**
